# syntax=docker/dockerfile:1.7@sha256:a57df69d0ea827fb7266491f2813635de6f17269be881f696fbfdf2d83dda33e

ARG GENTOO_IMAGE=gentoo/stage3@sha256:b5317fd2127e15ace5ff7a2c8aab1ed37a22736a8218546f3b00b4d94b78e500
ARG PORTAGE_IMAGE=gentoo/portage@sha256:6c49dbf51f9e52e3edeb43ca83e79025394b0a9b4c6cab1ed2b2f629e05c78e8

FROM ${PORTAGE_IMAGE} AS portage

FROM ${GENTOO_IMAGE}

COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo

RUN emerge --verbose --oneshot --getbinpkg=y \
        dev-lang/go \
        dev-util/pkgcheck \
        dev-vcs/git \
        app-arch/zstd \
        app-misc/ca-certificates \
        sys-apps/coreutils \
        sys-apps/gptfdisk \
        sys-apps/util-linux \
        sys-fs/e2fsprogs

COPY metadata /var/db/repos/volatoo/metadata
COPY profiles /var/db/repos/volatoo/profiles
COPY sys-apps /var/db/repos/volatoo/sys-apps
COPY sys-kernel /var/db/repos/volatoo/sys-kernel
WORKDIR /var/db/repos/volatoo

RUN pkgcheck scan
